name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Restore
      run: dotnet restore

    - name: Setup auth feed
      run: dotnet nuget add source https://nuget.telerik.com/nuget -n Telerik -u ${{ secrets.AUTH_FEED_USER }} -p ${{ secrets.AUTH_FEED_PWD }} --store-password-in-clear-text

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_NAME }} -r linux-x64

    - name: Build with dotnet
      run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore -r linux-x64 --self-contained true
